let currentLang = 'es';

const translations = {
  es: {
    metaTitle: "Masajistas Privé | Portal Exclusivo de Masajes en Buenos Aires",
    exit: "Salir",
    searchBtn: "Buscar",
    drawerTitle: "Buscador & Filtros",
    lblName: "Buscar por Nombre o Servicio",
    lblNamePh: "Escribí un nombre o técnica...",
    lblZone: "Filtrar por Zona / Barrio",
    optAllZones: "Todos los Barrios",
    lblCat: "Seleccionar Categoría",
    optAllCats: "Todas las Categorías",
    optCatSens: "Sensuales",
    optCatTerap: "Terapéuticas",
    optCatMasc: "Masculinos",
    optCatFant: "Fantasías",
    btnResults: "Ver Resultados",
    ageTitle: "Este es un sitio para adultos",
    ageDesc: "Este sitio contiene material para adultos. Al ingresar declarás que tenés al menos 18 años y aceptás nuestros términos y condiciones.<br><br><strong>Aviso:</strong> Las masajistas anunciantes no tienen ningún vínculo laboral con este portal; somos únicamente un soporte publicitario.",
    ageEnter: "ENTRAR (+18)",
    ageExit: "SALIR",
    tabAll: "Todas",
    tabSens: "Sensuales",
    tabTerap: "Terapéuticas",
    tabMasc: "Masculinos",
    tabFant: "Fantasías",
    tabForum: "💬 Foro",
    catSensTitle: "Masajistas Sensuales",
    catTerapTitle: "Masajistas Terapéuticas",
    catMascTitle: "Masajistas Masculinos",
    catFantTitle: "Fantasías",
    bannerTitle: "Publicitá tu espacio aquí",
    bannerDesc: "Alquiler de gabinetes equipados o incorporación a la nómina de profesionales. ¡Publicación 100% gratuita hasta el 30/09!",
    bannerBtn: "Consultar Ahora",
    cardSp1: "Espacio Disponible",
    cardSp2: "Publicación gratis hasta el 30/09",
    cardSp3: "Anunciarme",
    cardFree1: "Espacio Libre",
    cardFree2: "Anunciarme",
    cardPub1: "Publicá Tu Anuncio",
    cardPub2: "100% sin cargo hasta el 30/09",
    cardPub3: "Anunciarme",
    cardFan1: "Espacio Disponible",
    cardFan2: "Publicá tus sesiones especiales",
    cardFan3: "Anunciarme",
    cardFan4: "Publicá Tu Anuncio",
    cardFan5: "Perfil con verificación transparente",
    cardFan6: "Anunciarme",
    forumTitle: "💬 Foro & Comunidad Privé",
    forumSub: "Espacio de Debate",
    forumRules: "<strong>Normas del Foro:</strong> Mantené el respeto y la cordialidad. Se prohíbe divulgar datos personales privados, spam directo o contenido ofensivo. Las opiniones pertenecen exclusivamente a los usuarios.",
    noThreads: "Aún no hay temas creados en la comunidad. ¡Sé el primero en iniciar un debate!",
    newThreadTitle: "Crear un nuevo tema de debate",
    newThreadPh: "Título del tema o pregunta...",
    optFRec: "Recomendaciones de Zonas / Gabinetes",
    optFTec: "Consultas sobre Técnicas de Masajes",
    optFGen: "Debate General & Experiencias",
    newThreadBodyPh: "Escribí tu consulta o aporte a la comunidad...",
    btnCreateThread: "Publicar Tema",
    trustTitle: "🛡️ Compromiso de Calidad & Seguridad",
    trustUserH: "Guía para Usuarios",
    trustUserList: "<li>Coordinación transparente y directa vía WhatsApp sin intermediarios.</li><li>Respeto mutuo y trato cordial durante la atención en gabinete.</li><li>Cancelaciones con aviso previo para optimizar la agenda de las profesionales.</li>",
    trustProtoH: "Protocolo de Verificación",
    trustProtoP: "El sello <strong>✓ Privé Verificado</strong> garantiza la autenticidad del material fotográfico mediante validación previa de identidad, protegiendo a los usuarios contra perfiles falsos.",
    verifiedTag: "✓ Sello Oficial Privé Verificado",
    lblMod: "Modalidad / Zona",
    lblBio: "Descripción",
    lblSch: "Días y Horarios",
    lblEq: "Equipamiento y Servicios",
    lblServ: "Técnicas de Masaje",
    lblPay: "Medios de Pago",
    lblBook: "Modalidad de Turnos",
    btnCall: "📞 Contactar Telefónicamente",
    btnWa: "💬 Contactar por WhatsApp",
    expTitle: "Casilla de Experiencias",
    expRules: "Publicá tu experiencia con respeto y cordialidad hacia las profesionales y la comunidad. Comentarios ofensivos serán eliminados.",
    expAuthorPh: "Tu nombre o apodo...",
    expTextPh: "Escribí tu reseña o experiencia aquí...",
    btnSubmitExp: "Publicar Experiencia",
    floatingCta: "¿Querés Publicar?",
    footer: "<strong>DESCARGO DE RESPONSABILIDAD LEGAL:</strong> MasajistasPrivé.com funciona únicamente como un soporte publicitario digital independiente. El sitio no emplea, representa ni intermedia en la contratación de los anunciantes listados. Toda la información suministrada en los avisos es de exclusiva responsabilidad de cada anunciante. MasajistasPrivé.com se deslinda de cualquier responsabilidad legal respecto a la veracidad de los anuncios o el desarrollo de los servicios prestados por terceros."
  },
  en: {
    metaTitle: "Masajistas Privé | Exclusive Massage Portal in Buenos Aires",
    exit: "Exit",
    searchBtn: "Search",
    drawerTitle: "Search & Filters",
    lblName: "Search by Name or Service",
    lblNamePh: "Type a name or technique...",
    lblZone: "Filter by Zone / Neighborhood",
    optAllZones: "All Neighborhoods",
    lblCat: "Select Category",
    optAllCats: "All Categories",
    optCatSens: "Sensual",
    optCatTerap: "Therapeutic",
    optCatMasc: "Male",
    optCatFant: "Fantasies",
    btnResults: "View Results",
    ageTitle: "This is an adult site",
    ageDesc: "This portal contains adult material. By entering, you confirm you are at least 18 years old and accept our terms of service.<br><br><strong>Notice:</strong> Advertising masseuses have no employment relationship with this portal; we are solely an advertising medium.",
    ageEnter: "ENTER (+18)",
    ageExit: "EXIT",
    tabAll: "All",
    tabSens: "Sensual",
    tabTerap: "Therapeutic",
    tabMasc: "Male",
    tabFant: "Fantasies",
    tabForum: "💬 Forum",
    catSensTitle: "Sensual Masseuses",
    catTerapTitle: "Therapeutic Masseuses",
    catMascTitle: "Male Masseurs",
    catFantTitle: "Fantasies",
    bannerTitle: "Advertise your space here",
    bannerDesc: "Rental of equipped studios or joining the exclusive roster of professionals. 100% free publication until 09/30!",
    bannerBtn: "Inquire Now",
    cardSp1: "Available Space",
    cardSp2: "Free publication until 09/30",
    cardSp3: "Advertise",
    cardFree1: "Free Space",
    cardFree2: "Advertise",
    cardPub1: "Publish Your Ad",
    cardPub2: "100% free until 09/30",
    cardPub3: "Advertise",
    cardFan1: "Available Space",
    cardFan2: "Publish your special sessions",
    cardFan3: "Advertise",
    cardFan4: "Publish Your Ad",
    cardFan5: "Profile with transparent verification",
    cardFan6: "Advertise",
    forumTitle: "💬 Privé Community Forum",
    forumSub: "Discussion Space",
    forumRules: "<strong>Forum Rules:</strong> Maintain respect and cordiality. Disseminating private personal data, direct spam, or offensive content is prohibited. Opinions belong exclusively to the users.",
    noThreads: "No threads created in the community yet. Be the first to start a discussion!",
    newThreadTitle: "Create a new discussion topic",
